In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel("datasets/study_hours.xlsx")
df

Sleep_hours  Study_Hours  Test_score
0            3            5          75
1            5            1          82
2           10            2          93

In [3]:
X = df.iloc[:,:2]
X = np.array(X)
print(X)

[[ 3  5]
 [ 5  1]
 [10  2]]


In [4]:
y = df.iloc[:,2:3]
y = np.array(y)
print(y)

[[75]
 [82]
 [93]]


In [5]:
X = X/np.amax(X,axis=0) #maximum of X array longitudinally
y = y/100
print(X, y)

[[0.3 1. ]
 [0.5 0.2]
 [1.  0.4]] [[0.75]
 [0.82]
 [0.93]]


In [6]:
#Sigmoid Function (Activation Function)
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [7]:
#Variable initialization
epoch = 100
learning_rate = 1
ip_neurons = 2
hidden_neurons = 2
op_neurons = 1

In [8]:
#Weight and Bias Initialization
wh = np.random.uniform(size = (ip_neurons, hidden_neurons))
bh = np.random.uniform(size = (1, hidden_neurons))
wout = np.random.uniform(size = (hidden_neurons, op_neurons))
bout = np.random.uniform(size = (1, op_neurons))

print(bh)
print(bout)
res = []

[[0.3223773  0.71658968]]
[[0.52048842]]


In [9]:
#draws a random range of numbers uniformly of dim x*Y
for no in range(len(X)):
    print(no)
    x = np.array(X[no], ndmin = 2)
    print(x)
    Y = np.array(y[no], ndmin = 2)
    print(Y)
    for i in range(epoch):
        #1. Forward Propogation
        hinp1 = np.dot(x, wh)
        hinp = hinp1 + bh
        hlayer_act = sigmoid(hinp)
        outinp1 = np.dot(hlayer_act, wout)
        outinp = outinp1 + bout
        output = sigmoid(outinp)
        #2. Backpropagation
        d_output = (Y - output) * output * (1 - output)
        # hidden layer wts contributed to error
        d_hiddenlayer = d_output.dot(wout.T) * (hlayer_act) * (1 - hlayer_act)
    
        #3. adjust Weight and bias
        wout = wout + hlayer_act.T.dot(d_output) * learning_rate # delta*output*learning rate
        wh = wh + x.T.dot(d_hiddenlayer) * learning_rate
        print("-----------Epoch-", i + 1)
        print("Input: \n" + str(x) + "Actual Output: \n" + str(Y) + "Predicted Output: \n", output)
    res.append(output)
    print("Input: \n" + str(x) + "Actual Output: \n" + str(Y) + "Final Predicted Output: \n", output)

0
[[0.3 1. ]]
[[0.75]]
-----------Epoch- 1
Input: 
[[0.3 1. ]]Actual Output: 
[[0.75]]Predicted Output: 
 [[0.73857735]]
-----------Epoch- 2
Input: 
[[0.3 1. ]]Actual Output: 
[[0.75]]Predicted Output: 
 [[0.73907188]]
-----------Epoch- 3
Input: 
[[0.3 1. ]]Actual Output: 
[[0.75]]Predicted Output: 
 [[0.73954392]]
-----------Epoch- 4
Input: 
[[0.3 1. ]]Actual Output: 
[[0.75]]Predicted Output: 
 [[0.73999458]]
-----------Epoch- 5
Input: 
[[0.3 1. ]]Actual Output: 
[[0.75]]Predicted Output: 
 [[0.74042492]]
-----------Epoch- 6
Input: 
[[0.3 1. ]]Actual Output: 
[[0.75]]Predicted Output: 
 [[0.74083592]]
-----------Epoch- 7
Input: 
[[0.3 1. ]]Actual Output: 
[[0.75]]Predicted Output: 
 [[0.74122853]]
-----------Epoch- 8
Input: 
[[0.3 1. ]]Actual Output: 
[[0.75]]Predicted Output: 
 [[0.74160362]]
-----------Epoch- 9
Input: 
[[0.3 1. ]]Actual Output: 
[[0.75]]Predicted Output: 
 [[0.74196205]]
-----------Epoch- 10
Input: 
[[0.3 1. ]]Actual Output: 
[[0.75]]Predicted Output: 
 [[0.7423045

In [10]:
print(res)

[array([[0.74982872]]), array([[0.81588518]]), array([[0.9085581]])]
